### ISSUE TITLE
CodeOverview story is broken: _fetchAndLoadComments is not a function

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1315]
### Describe the problem and steps to reproduce it:

Go to https://mozilla.github.io/addons-code-manager/?path=/story/codeoverview--short-file

### What happened?

The story produces this error:

```
_fetchAndLoadComments is not a function
```

In the debugger, I can see that all imports from `../../reducers/comments` at the top of `CommentList/index.tsx` are undefined.

### What did you expect to happen?

It should load the story

### Anything else we should know?

git bisect says that https://github.com/mozilla/addons-code-manager/commit/76fdcaeb0d1ae06c87f996ba28e96ad425f7bb25 introduced the problem but it's not obvious why.

There is maybe some kind of storybook bug or webpack misconfiguration or who knows what. As a clue, I can make the error go away like this:

<details>
<summary>Patch</summary>

```diff
diff --git a/src/components/DiffView/index.tsx b/src/components/DiffView/index.tsx
index 49d9fb8..9cc1590 100644
--- a/src/components/DiffView/index.tsx
+++ b/src/components/DiffView/index.tsx
@@ -19,7 +19,6 @@ import { withRouter, RouteComponentProps } from 'react-router-dom';
 import makeClassName from 'classnames';
 
 import Commentable from '../Commentable';
-import CommentList from '../CommentList';
 import FadableContent from '../FadableContent';
 import LinterProvider, { LinterProviderInfo } from '../LinterProvider';
 import LinterMessage from '../LinterMessage';
@@ -40,6 +39,8 @@ import {
 import styles from './styles.module.scss';
 import 'react-diff-view/style/index.css';
 
+const CommentList = () => <div />;
+
 // This is the number of changes for which a diff starts loading slowly,
 // even when syntax highlighting is disabled.
 const SLOW_DIFF_CHANGE_COUNT = 1000;

```

</details>

**Comment by kumar303** [comment]
This is yet another bug that https://github.com/mozilla/addons-code-manager/issues/425 probably would have caught.

**Comment by mirefly** [comment]
It looks like that db4962c fixed this.

**Comment by willdurand** [comment]
thanks @mirefly

**Comment by ioanarusiczki** [comment]
@mirefly The page loads without errors. 

![without errors](https://user-images.githubusercontent.com/33448286/71409547-a7a0f380-264a-11ea-9709-292f6162c395.png)
